# Generated by Django 5.2.1 on 2025-06-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_projectmanagerassignment'),
        ('project_management', '0002_project_projectmember_subtask_task_delete_projects_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'employee'), name='unique_project_member'),
        ),
    ]
