# Generated by Django 5.2.1 on 2025-06-25 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_projectmanagerassignment_unique_pm_developer_assignment_and_more'),
        ('project_management', '0003_alter_projectmember_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_made', to='employee.employee')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_audits', to='employee.employee')),
                ('new_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employee.employee')),
                ('previous_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employee.employee')),
            ],
        ),
    ]
