# Generated by Django 5.2.1 on 2025-06-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0005_project_is_active_project_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
