# Generated by Django 5.2.1 on 2025-06-26 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_projectmanagerassignment_unique_pm_developer_assignment_and_more'),
        ('project_management', '0010_taskassignmentaudit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssignmentAuditLog',
            new_name='DeveloperAssignmentAuditLog',
        ),
    ]
