# Generated by Django 5.2.1 on 2025-07-06 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_projectmanagerassignment_unique_pm_developer_assignment_and_more'),
        ('project_management', '0011_rename_assignmentauditlog_developerassignmentauditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_pm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee'),
        ),
    ]
