# Generated by Django 5.2.1 on 2025-07-10 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0014_subtask_labels_task_labels_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.DeleteModel(
            name='TaskAssignmentAudit',
        ),
    ]
