# Generated by Django 5.2.1 on 2025-07-10 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_employee_role'),
        ('project_management', '0015_remove_task_assigned_to_delete_taskassignmentaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='employee.employee'),
        ),
    ]
