# Generated by Django 5.2.1 on 2025-07-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_employee_role'),
        ('project_management', '0016_alter_subtask_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=3, max_digits=5, null=True),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('name', 'description'), name='unique_project_name_description'),
        ),
        migrations.AddConstraint(
            model_name='subtask',
            constraint=models.UniqueConstraint(fields=('task', 'title', 'description'), name='unique_subtask_per_task'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('title', 'project'), name='unique_task_title_per_project'),
        ),
    ]
