# Generated by Django 5.2.1 on 2025-07-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0017_subtask_estimated_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
