# Generated by Django 5.2.1 on 2025-10-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0018_alter_subtask_estimated_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(default='#3498db', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
