# Generated by Django 5.2.1 on 2025-06-02 09:07

import shared_apps.custom_auth.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_tenantuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', shared_apps.custom_auth.managers.CustomUserManager()),
            ],
        ),
    ]
