# Generated by Django 5.2.1 on 2025-06-25 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to='employee.employee')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_pm', to='employee.employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devs_under_pm', to='employee.employee')),
            ],
        ),
    ]
