# Generated by Django 5.2.1 on 2025-06-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_projectmanagerassignment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectmanagerassignment',
            constraint=models.UniqueConstraint(fields=('manager', 'developer'), name='unique_pm_developer_assignment'),
        ),
    ]
