# Generated by Django 5.2.1 on 2025-06-25 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_projectmanagerassignment_unique_pm_developer_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanagerassignment',
            name='developer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_pm', to='employee.employee'),
        ),
    ]
