# Generated by Django 5.2.1 on 2025-07-10 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_employee_role_employee_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
    ]
