# Generated by Django 5.2.1 on 2025-07-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='tenant',
        ),
    ]
