# Generated by Django 5.2.1 on 2025-07-21 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_remove_employee_tenant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
